import type { Category, ItemCondition, Tag, ValueRange } from "./types";

export const categories: Category[] = [
  { id: "cat-electronics", name: "Electrónicos", slug: "electronicos" },
  { id: "cat-phones", name: "Celulares", slug: "celulares" },
  { id: "cat-computers", name: "Computadoras y laptops", slug: "computadoras-laptops" },
  { id: "cat-gaming", name: "Videojuegos y consolas", slug: "videojuegos-consolas" },
  { id: "cat-tools", name: "Herramientas", slug: "herramientas" },
  { id: "cat-bikes", name: "Bicicletas", slug: "bicicletas" },
  { id: "cat-audio", name: "Audio", slug: "audio" },
  { id: "cat-music", name: "Instrumentos musicales", slug: "instrumentos-musicales" },
  { id: "cat-furniture", name: "Muebles pequeños", slug: "muebles-pequenos" },
  { id: "cat-fashion", name: "Ropa y sneakers", slug: "ropa-sneakers" },
  { id: "cat-books", name: "Libros", slug: "libros" },
  { id: "cat-toys", name: "Juguetes", slug: "juguetes" },
  { id: "cat-collectibles", name: "Coleccionables", slug: "coleccionables" },
  { id: "cat-photo", name: "Fotografía", slug: "fotografia" },
  { id: "cat-sports", name: "Deportes", slug: "deportes" },
  { id: "cat-home", name: "Hogar", slug: "hogar" },
  { id: "cat-appliances", name: "Electrodomesticos", slug: "electrodomesticos" },
  { id: "cat-kitchen", name: "Cocina", slug: "cocina" },
  { id: "cat-baby-kids", name: "Bebes y ninos", slug: "bebes-ninos" },
  { id: "cat-pet-supplies", name: "Articulos para mascotas", slug: "articulos-mascotas" },
  { id: "cat-art-crafts", name: "Arte y manualidades", slug: "arte-manualidades" },
  { id: "cat-board-games", name: "Juegos de mesa", slug: "juegos-de-mesa" },
  { id: "cat-auto-moto", name: "Autos y motos", slug: "autos-motos" },
  { id: "cat-beauty", name: "Belleza y cuidado", slug: "belleza-cuidado" },
  { id: "cat-travel", name: "Viaje y maletas", slug: "viaje-maletas" },
  { id: "cat-garden", name: "Plantas y jardin", slug: "plantas-jardin" },
  { id: "cat-other", name: "Otros", slug: "otros" },
];

export const privateInterestTags: Tag[] = [
  { id: "tag-phones", name: "Celulares", slug: "celulares" },
  { id: "tag-tablets", name: "Tablets", slug: "tablets" },
  { id: "tag-laptops", name: "Laptops", slug: "laptops" },
  { id: "tag-monitors", name: "Monitores", slug: "monitores" },
  { id: "tag-keyboards-mice", name: "Teclados y mouse", slug: "teclados-mouse" },
  { id: "tag-computer-accessories", name: "Accesorios de computo", slug: "accesorios-computo" },
  { id: "tag-consoles", name: "Consolas", slug: "consolas" },
  { id: "tag-video-games", name: "Videojuegos", slug: "videojuegos" },
  { id: "tag-tools", name: "Herramientas", slug: "herramientas" },
  { id: "tag-power-tools", name: "Herramientas electricas", slug: "herramientas-electricas" },
  { id: "tag-auto-parts", name: "Refacciones", slug: "refacciones" },
  { id: "tag-bikes", name: "Bicicletas", slug: "bicicletas" },
  { id: "tag-scooters", name: "Scooters", slug: "scooters" },
  { id: "tag-audio", name: "Audio", slug: "audio" },
  { id: "tag-headphones", name: "Audifonos", slug: "audifonos" },
  { id: "tag-smartwatches", name: "Smartwatches", slug: "smartwatches" },
  { id: "tag-home", name: "Hogar", slug: "hogar" },
  { id: "tag-furniture", name: "Muebles", slug: "muebles" },
  { id: "tag-home-decor", name: "Decoracion", slug: "decoracion" },
  { id: "tag-appliances", name: "Electrodomesticos", slug: "electrodomesticos" },
  { id: "tag-kitchen", name: "Cocina", slug: "cocina" },
  { id: "tag-sneakers", name: "Sneakers", slug: "sneakers" },
  { id: "tag-brand-clothes", name: "Ropa de marca", slug: "ropa-de-marca" },
  { id: "tag-accessories", name: "Accesorios", slug: "accesorios" },
  { id: "tag-beauty", name: "Belleza y cuidado", slug: "belleza-cuidado" },
  { id: "tag-instruments", name: "Instrumentos", slug: "instrumentos" },
  { id: "tag-collectibles", name: "Coleccionables", slug: "coleccionables" },
  { id: "tag-photo", name: "Fotografía", slug: "fotografia" },
  { id: "tag-cameras", name: "Camaras", slug: "camaras" },
  { id: "tag-drones", name: "Drones", slug: "drones" },
  { id: "tag-camping", name: "Camping", slug: "camping" },
  { id: "tag-sports", name: "Deportes", slug: "deportes" },
  { id: "tag-fitness", name: "Fitness", slug: "fitness" },
  { id: "tag-toys", name: "Juguetes", slug: "juguetes" },
  { id: "tag-board-games", name: "Juegos de mesa", slug: "juegos-de-mesa" },
  { id: "tag-baby-kids", name: "Bebes y ninos", slug: "bebes-ninos" },
  { id: "tag-books", name: "Libros", slug: "libros" },
  { id: "tag-comics-manga", name: "Comics y manga", slug: "comics-manga" },
  { id: "tag-vinyl-music", name: "Vinilos y musica", slug: "vinilos-musica" },
  { id: "tag-art-crafts", name: "Arte y manualidades", slug: "arte-manualidades" },
  { id: "tag-stationery", name: "Papeleria", slug: "papeleria" },
  { id: "tag-backpacks", name: "Mochilas", slug: "mochilas" },
  { id: "tag-luggage", name: "Maletas", slug: "maletas" },
  { id: "tag-pet-supplies", name: "Articulos para mascotas", slug: "articulos-mascotas" },
  { id: "tag-garden", name: "Plantas y jardin", slug: "plantas-jardin" },
  { id: "tag-other", name: "Otros", slug: "otros" },
];

export const conditionLabels: Record<ItemCondition, string> = {
  new: "Nuevo",
  like_new: "Como nuevo",
  used_good: "Usado en buen estado",
  used_with_details: "Usado con detalles",
  works_with_issues: "Funciona con fallas",
  for_repair: "Para reparar",
  not_working_parts: "No funciona / para piezas",
};

export const valueRangeLabels: Record<ValueRange, string> = {
  under_500: "Menos de $500 MXN",
  "500_1500": "$500 a $1,500 MXN",
  "1500_3000": "$1,500 a $3,000 MXN",
  "3000_7000": "$3,000 a $7,000 MXN",
  "7000_15000": "$7,000 a $15,000 MXN",
  over_15000: "Más de $15,000 MXN",
  prefer_not_to_say: "Prefiero no decir",
};

export const rejectionReasons = [
  "No me interesa",
  "La oferta no me convence",
  "Está muy lejos",
  "Ya no está disponible",
  "Busco algo diferente",
  "Otro motivo",
  "Rechazar sin motivo",
];

export const prohibitedItemExamples = [
  "Armas de fuego",
  "Municiones",
  "Explosivos",
  "Medicamentos controlados",
  "Drogas",
  "Alcohol",
  "Tabaco, vapes o nicotina",
  "Animales",
  "Documentos oficiales",
  "Productos robados",
  "Réplicas o productos falsificados",
  "Datos personales de terceros",
];

export const forbiddenTradeRequestFieldNames = [
  "amount",
  "cash",
  "currency",
  "delivery",
  "deposit",
  "envio",
  "envío",
  "fee",
  "money",
  "monto",
  "paqueteria",
  "paquetería",
  "payment",
  "pago",
  "price",
  "shipping",
];
